language: java
jdk:
  - oraclejdk9
sudo: false
install: true
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notifications:
  email:
    recipients:
      - 20145523.sw.cau@gmail.com
    on_success: change
    on_failure: never
